name: PR check

on:
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'


      - name: Install Corepack
        run:  npm install -g corepack

      - name: Enable Corepack   
        run: corepack enable
  
      - name: Prepare Yarn
        run: |
          corepack prepare yarn@4.3.1 --activate
          yarn --version
  
      - name: Install dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint

      - name: Run type check
        run: yarn typecheck

      - name: Run build
        run: yarn build











        